AWSTemplateFormatVersion: 2010-09-09

Description: >-
  + CDN with static file caching
  + Certificate for our domain name

Parameters:
  HerokuOrigin:
    Type: String
  DomainName:
    Type: String
    Default: sam.irish

Resources:
  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFront
    Properties: 
      Name: !Ref DomainName
      Comment: Points our domain name at our cloudfront distribution
      Type: A
      HostedZoneName: !Sub "${DomainName}."
      AliasTarget:
        DNSName: !GetAtt CloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # default HostedZoneId for Cloudfront

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS

  CloudFront:
    Type: AWS::CloudFront::Distribution
    DependsOn: Certificate
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        CacheBehaviors:
          - DefaultTTL: 31622400
            MaxTTL: 31622400
            MinTTL: 31622400
            PathPattern: "favicon.ico"
            ForwardedValues:
              QueryString: false
              Headers:
                - Host
            CachedMethods:
              - GET
              - HEAD
            AllowedMethods:
              - GET
              - HEAD
            ViewerProtocolPolicy: allow-all
            Compress: true
            TargetOriginId: herokuOrigin
          - DefaultTTL: 31622400
            MaxTTL: 31622400
            MinTTL: 31622400
            PathPattern: "css/*.css"
            ForwardedValues:
              QueryString: false
              Headers:
                - Host
            CachedMethods:
              - GET
              - HEAD
            AllowedMethods:
              - GET
              - HEAD
            ViewerProtocolPolicy: allow-all
            Compress: true
            TargetOriginId: herokuOrigin
          - DefaultTTL: 31622400
            MaxTTL: 31622400
            MinTTL: 31622400
            PathPattern: "js/*.js"
            ForwardedValues:
              QueryString: false
              Headers:
                - Host
            CachedMethods:
              - GET
              - HEAD
            AllowedMethods:
              - GET
              - HEAD
            ViewerProtocolPolicy: https-only
            Compress: true
            TargetOriginId: herokuOrigin
          - DefaultTTL: 31622400
            MaxTTL: 31622400
            MinTTL: 31622400
            PathPattern: "images/*"
            ForwardedValues:
              QueryString: false
              Headers:
                - Host
            CachedMethods:
              - GET
              - HEAD
            AllowedMethods:
              - GET
              - HEAD
            ViewerProtocolPolicy: https-only
            Compress: true
            TargetOriginId: herokuOrigin
        Origins:
          - DomainName: !Ref HerokuOrigin
            Id: herokuOrigin
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          ForwardedValues:
            QueryString: true
            Headers:
              - Host
            Cookies:
              Forward: all
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: herokuOrigin
        Enabled: true
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016

Outputs:
  CloudFrontDomainName:
    Value: !GetAtt CloudFront.DomainName

  CertificateArn:
    Value: !Ref Certificate
